import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { viteSingleFile } from 'vite-plugin-singlefile'
import { readFileSync } from 'node:fs'

// Ships src/version.json as a standalone dist/version.json so long-lived open
// sessions can poll it and offer a refresh when a newer build is deployed.
// Reading the same committed file the bundle imports keeps the two in lockstep.
function emitVersionEndpoint() {
  return {
    name: 'emit-version-endpoint',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'version.json',
        source: readFileSync(new URL('./src/version.json', import.meta.url), 'utf8'),
      })
    },
  }
}

// The version string comes from the committed src/version.json (generated by
// gen-version.mjs), NOT from git here — Vercel shallow-clones and would miscount.

// Builds the whole app (JS, CSS, images, data) into ONE self-contained index.html
// that runs by double-clicking — no server needed.
export default defineConfig({
  plugins: [react(), viteSingleFile(), emitVersionEndpoint()],
  base: './',
  server: {
    port: 3000
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    assetsInlineLimit: 100000000,
    cssCodeSplit: false
  }
})
