// Regenerates the bundled data snapshot + banner images used by the single-file app.
// Run via RefreshApp.bat (which then rebuilds InlandCutoffGuide.html).
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const XLSX = require('xlsx');
const sharp = require('sharp');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'frontend/src/data');
const SOURCE_STATUS_PATH = path.join(__dirname, '.last-master-source.json');
const { readStableWorkbook, buildMasterData } = require('./master-workbook');
const writeJson = (name, value) => fs.writeFileSync(path.join(DATA_DIR, name), `${JSON.stringify(value, null, 2)}\n`);

// 1) Export the Excel DATABASE sheet -> frontend/src/data/lanes.json
// Two master sources: EXCEL_PATH (the OneDrive-synced SharePoint copy — kept
// fresh automatically while the owner is signed in) and EXCEL_PATH_FALLBACK
// (the Z: network share the manual Managers Hub publish deposits to). The
// SharePoint copy is always tried first. Z: is used only when the primary copy
// is missing, still syncing, unreadable, or fails workbook/data validation.
const candidates = [
  { kind: 'primary', path: process.env.EXCEL_PATH },
  { kind: 'fallback', path: process.env.EXCEL_PATH_FALLBACK },
].filter(candidate => candidate.path);

let selected;
let masterData;
const candidateErrors = [];
for (const candidate of candidates) {
  try {
    const loaded = readStableWorkbook(candidate);
    const data = buildMasterData(loaded.wb);
    selected = loaded;
    masterData = data;
    break;
  } catch (error) {
    const message = `${candidate.kind} master rejected (${candidate.path}): ${error.message}`;
    candidateErrors.push(message);
    console.warn(`  WARNING: ${message}`);
  }
}
if (!selected || !masterData) {
  console.error(`ERROR: no valid master workbook. ${candidateErrors.join(' | ')}`);
  process.exit(1);
}

fs.mkdirSync(DATA_DIR, { recursive: true });
writeJson('lanes.json', masterData.lanes);
writeJson('holidays.json', masterData.holidays);
writeJson('portmc.json', masterData.portmc);
writeJson('port-services.json', masterData.portServices);

const sourceStatus = {
  schema: 1,
  kind: selected.kind,
  sourceHash: crypto.createHash('sha256').update(selected.buffer).digest('hex').toUpperCase(),
  fileSize: selected.stat.size,
  modifiedAt: selected.stat.mtime.toISOString(),
  selectedAt: new Date().toISOString(),
  laneCount: masterData.lanes.length,
};
fs.writeFileSync(SOURCE_STATUS_PATH, `${JSON.stringify(sourceStatus, null, 2)}\n`);

console.log(`  Master: ${selected.kind} ${selected.path}`);
console.log(`  Data: validated ${masterData.lanes.length} lanes from ${selected.stat.size} bytes`);
console.log(`  Holidays: ${Object.entries(masterData.holidays).map(([country, dates]) => `${country}=${dates.length}`).join(', ')}`);
console.log(`  PORTMC: ${Object.keys(masterData.portmc).length} ports`);
console.log(`  PORTSERVICES: ${Object.keys(masterData.portServices).length} POL service rules`);

// 2) Convert the current banners (from /public) to WebP and embed as data URIs.
// The 10-minute watcher skips this deterministic image work; RefreshApp.bat
// still performs it when rebuilding the complete offline guide manually.
const publicDir = path.join(ROOT, 'public');

async function toWebpDataUri(file) {
  const buf = await sharp(path.join(publicDir, file)).webp({ quality: 82 }).toBuffer();
  return 'data:image/webp;base64,' + buf.toString('base64');
}

const refreshBanners = async () => {
  const topUri = await toWebpDataUri('truck-highway-sunset.png'); // truck banner on top (unchanged)
  const botUri = await toWebpDataUri('train-bridge.png');         // vessel-bridge banner on bottom
  const botImgUri = await toWebpDataUri('ob-bot.png'); // OB the OPS-BASE BOT (mobile gatekeeper)
  const banners =
    '// Images embedded as WebP data URIs so the app builds into a single self-contained file.\n' +
    '// Auto-generated by backend/refresh-data.js — do not edit by hand.\n' +
    'export const bannerTop = "' + topUri + '";\n' +
    'export const bannerBottom = "' + botUri + '";\n' +
    'export const obBot = "' + botImgUri + '";\n';
  const assetsDir = path.join(ROOT, 'frontend/src/assets');
  fs.mkdirSync(assetsDir, { recursive: true });
  fs.writeFileSync(path.join(assetsDir, 'banners.js'), banners);
  console.log('  Images: converted to WebP + embedded (banners + ob-bot)');
};

if (process.argv.includes('--skip-banners')) {
  console.log('  Images: skipped for scheduled data check');
} else {
  refreshBanners().catch(error => {
    console.error(`ERROR: image refresh failed: ${error.message}`);
    process.exitCode = 1;
  });
}
