// Regenerates the bundled data snapshot + banner images used by the single-file app.
// Run via RefreshApp.bat (which then rebuilds InlandCutoffGuide.html).
const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');
const sharp = require('sharp');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const ROOT = path.join(__dirname, '..');

// 1) Export the Excel DATABASE sheet -> frontend/src/data/lanes.json
const excelPath = process.env.EXCEL_PATH;
if (!excelPath || !fs.existsSync(excelPath)) {
  console.error('ERROR: Excel not found at EXCEL_PATH:', excelPath);
  process.exit(1);
}

const wb = XLSX.readFile(excelPath);
const rows = XLSX.utils.sheet_to_json(wb.Sheets['DATABASE'], { header: 1 });
const lanes = [];
let inData = false;
for (let i = 0; i < rows.length; i++) {
  if (rows[i][0] === 'STARTDATA') { inData = true; continue; }
  if (rows[i][0] === 'ENDDATA' || !inData) continue;
  if (rows[i][0]) {
    lanes.push({
      pol: rows[i][0], ssy: rows[i][1], name: rows[i][2], loccode: rows[i][3],
      rampMC: rows[i][4], rampCutTime: rows[i][5],
      transit: parseFloat(rows[i][6]) || 0, window: parseFloat(rows[i][7]) || 0,
      ssyAdjustment: parseFloat(rows[i][8]) || 0, reefer: rows[i][9],
      windowReefer: parseFloat(rows[i][10]) || 0
    });
  }
}
const dataDir = path.join(ROOT, 'frontend/src/data');
fs.mkdirSync(dataDir, { recursive: true });
fs.writeFileSync(path.join(dataDir, 'lanes.json'), JSON.stringify(lanes, null, 2));
console.log('  Data: wrote ' + lanes.length + ' lanes');

// 1b) Export the HOLIDAYS sheet -> frontend/src/data/holidays.json, grouped by country.
const holRows = XLSX.utils.sheet_to_json(wb.Sheets['HOLIDAYS'], { header: 1 });
const holidays = {};
for (const r of holRows) {
  const country = r[0];
  const serial = r[2];
  if ((country === 'US' || country === 'CA' || country === 'MX') && typeof serial === 'number') {
    const d = XLSX.SSF.parse_date_code(serial);
    const iso = d.y + '-' + String(d.m).padStart(2, '0') + '-' + String(d.d).padStart(2, '0');
    (holidays[country] = holidays[country] || []).push(iso);
  }
}
Object.keys(holidays).forEach(c => holidays[c].sort());
fs.writeFileSync(path.join(dataDir, 'holidays.json'), JSON.stringify(holidays, null, 2));
console.log('  Holidays: wrote ' + Object.entries(holidays).map(([c, a]) => c + '=' + a.length).join(', '));

// 2) Convert the current banners (from /public) to WebP and embed as data URIs.
const publicDir = path.join(ROOT, 'public');

async function toWebpDataUri(file) {
  const buf = await sharp(path.join(publicDir, file)).webp({ quality: 82 }).toBuffer();
  return 'data:image/webp;base64,' + buf.toString('base64');
}

(async () => {
  const topUri = await toWebpDataUri('truck-highway-sunset.png'); // truck banner on top (unchanged)
  const botUri = await toWebpDataUri('train-bridge.png');         // vessel-bridge banner on bottom
  const botImgUri = await toWebpDataUri('ob-bot.png'); // OB the OPS-BASE BOT (mobile gatekeeper)
  const banners =
    '// Images embedded as WebP data URIs so the app builds into a single self-contained file.\n' +
    '// Auto-generated by backend/refresh-data.js — do not edit by hand.\n' +
    'export const bannerTop = "' + topUri + '";\n' +
    'export const bannerBottom = "' + botUri + '";\n' +
    'export const obBot = "' + botImgUri + '";\n';
  const assetsDir = path.join(ROOT, 'frontend/src/assets');
  fs.mkdirSync(assetsDir, { recursive: true });
  fs.writeFileSync(path.join(assetsDir, 'banners.js'), banners);
  console.log('  Images: converted to WebP + embedded (banners + ob-bot)');
})();
