// Regenerates the bundled data snapshot + banner images used by the single-file app.
// Run via RefreshApp.bat (which then rebuilds InlandCutoffGuide.html).
const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');
const sharp = require('sharp');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const ROOT = path.join(__dirname, '..');

// 1) Export the Excel DATABASE sheet -> frontend/src/data/lanes.json
const excelPath = process.env.EXCEL_PATH;
if (!excelPath || !fs.existsSync(excelPath)) {
  console.error('ERROR: Excel not found at EXCEL_PATH:', excelPath);
  process.exit(1);
}

const wb = XLSX.readFile(excelPath);
const rows = XLSX.utils.sheet_to_json(wb.Sheets['DATABASE'], { header: 1 });
const lanes = [];
let inData = false;
for (let i = 0; i < rows.length; i++) {
  if (rows[i][0] === 'STARTDATA') { inData = true; continue; }
  if (rows[i][0] === 'ENDDATA' || !inData) continue;
  if (rows[i][0]) {
    lanes.push({
      pol: rows[i][0], ssy: rows[i][1], name: rows[i][2], loccode: rows[i][3],
      rampMC: rows[i][4], rampCutTime: rows[i][5],
      transit: parseFloat(rows[i][6]) || 0, window: parseFloat(rows[i][7]) || 0,
      ssyAdjustment: parseFloat(rows[i][8]) || 0, reefer: rows[i][9],
      windowReefer: parseFloat(rows[i][10]) || 0
    });
  }
}
const dataDir = path.join(ROOT, 'frontend/src/data');
fs.mkdirSync(dataDir, { recursive: true });
fs.writeFileSync(path.join(dataDir, 'lanes.json'), JSON.stringify(lanes, null, 2));
console.log('  Data: wrote ' + lanes.length + ' lanes');

// 2) Convert the current banners (from /public) to WebP and embed as data URIs.
const publicDir = path.join(ROOT, 'public');

async function toWebpDataUri(file) {
  const buf = await sharp(path.join(publicDir, file)).webp({ quality: 82 }).toBuffer();
  return 'data:image/webp;base64,' + buf.toString('base64');
}

(async () => {
  const topUri = await toWebpDataUri('truck-highway-sunset.png');
  const botUri = await toWebpDataUri('train-bridge.png');
  const banners =
    '// Banners embedded as WebP data URIs so the app builds into a single self-contained file.\n' +
    '// Auto-generated by backend/refresh-data.js — do not edit by hand.\n' +
    'export const bannerTop = "' + topUri + '";\n' +
    'export const bannerBottom = "' + botUri + '";\n';
  const assetsDir = path.join(ROOT, 'frontend/src/assets');
  fs.mkdirSync(assetsDir, { recursive: true });
  fs.writeFileSync(path.join(assetsDir, 'banners.js'), banners);
  console.log('  Banners: converted to WebP + embedded (truck-highway-sunset, train-bridge)');
})();
