// Read-only accessors over the committed CPKC port-schedule snapshot
// (frontend/src/data/cpkc-schedules.json), generated by scripts/refresh-cpkc.
// Unlike cutoff.js this does NO date math on the cutoffs themselves — those are
// published values read straight off the PDF. The only derived value is the ERD,
// which the PDF defines as a flat "5 days prior to the in-land cut-off date".
import schedules from '../data/cpkc-schedules.json';

const ERD_DAYS_BEFORE = 5;
const MONTHS = { Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5, Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11 };
const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const generatedAt = schedules.generatedAt || '';

// [{ slug, name }] for the port picker.
export function getPorts() {
  return Object.entries(schedules.ports || {}).map(([slug, p]) => ({ slug, name: p.name || slug }));
}

function port(slug) {
  return (schedules.ports || {})[slug] || null;
}

export function getPortInfo(slug) {
  const p = port(slug);
  if (!p) return null;
  return { name: p.name, runDate: p.runDate || '', generatedAt: p.generatedAt || generatedAt, notes: p.notes || [] };
}

// Vessel names in published order (services stay grouped as on the sheet).
export function getVessels(slug) {
  const p = port(slug);
  return p ? p.vessels.map(v => v.vessel) : [];
}

export function getCities(slug) {
  const p = port(slug);
  return p ? [...p.cities] : [];
}

export function getVesselMeta(slug, vessel) {
  const p = port(slug);
  return p ? p.vessels.find(v => v.vessel === vessel) || null : null;
}

// The published inland cutoff string, e.g. "Mon 29-Jun 18:30".
export function getCutoff(slug, vessel, city) {
  const v = getVesselMeta(slug, vessel);
  return v ? (v.cutoffs[city] || '') : '';
}

// Parse a "Mon 29-Jun 18:30" (or "Mon 29-Jun") cell into a local Date. The PDF
// omits the year, so pick the year (ref-1 / ref / ref+1) whose date lands closest
// to the schedule's own generation date — this survives Dec/Jan wrap-around.
export function parseCutoff(cutoffStr, refISO = generatedAt) {
  const m = String(cutoffStr).match(/(\d{1,2})-([A-Z][a-z]{2})(?:\s+(\d{1,2}):(\d{2}))?/);
  if (!m) return null;
  const day = Number(m[1]);
  const month = MONTHS[m[2]];
  if (month === undefined) return null;
  const hh = m[3] ? Number(m[3]) : 0;
  const mm = m[4] ? Number(m[4]) : 0;

  const [ry, rmo, rd] = String(refISO || '').split('-').map(Number);
  const ref = ry ? new Date(ry, (rmo || 1) - 1, rd || 1) : new Date(2000 + month, month, day);
  const refYear = ref.getFullYear();

  let best = null, bestDiff = Infinity;
  for (const y of [refYear - 1, refYear, refYear + 1]) {
    const d = new Date(y, month, day, hh, mm);
    const diff = Math.abs(d - ref);
    if (diff < bestDiff) { bestDiff = diff; best = d; }
  }
  return best;
}

function fmtDate(d) {
  return `${WEEKDAYS[d.getDay()]} ${d.getDate()}-${MONTH_NAMES[d.getMonth()]}`;
}

// ERD = the inland cutoff date minus 5 days (receiving opens), per the PDF note.
// Returned in the same "Www D-Mon" style the sheet uses. Empty if unparseable.
export function getERD(slug, vessel, city) {
  const cutoff = getCutoff(slug, vessel, city);
  const info = getPortInfo(slug);
  const d = parseCutoff(cutoff, info && info.generatedAt);
  if (!d) return '';
  d.setDate(d.getDate() - ERD_DAYS_BEFORE);
  return fmtDate(d);
}
