// Read-only accessors over the committed CPKC port-schedule snapshot
// (frontend/src/data/cpkc-schedules.json), generated by scripts/refresh-cpkc.
// Unlike cutoff.js this does NO date math on the cutoffs themselves — those are
// published values read straight off the PDF. The only derived value is the ERD,
// which the PDF defines as a flat "5 days prior to the in-land cut-off date".
import schedules from '../data/cpkc-schedules.json';

const ERD_DAYS_BEFORE = 5;
const MONTHS = { Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5, Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11 };
const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const generatedAt = schedules.generatedAt || '';
export const pulledAt = schedules.pulledAt || '';

// [{ slug, name, rail }] for the port picker.
export function getPorts() {
  return Object.entries(schedules.ports || {}).map(([slug, p]) => ({ slug, name: p.name || slug, rail: p.rail || '' }));
}

function port(slug) {
  return (schedules.ports || {})[slug] || null;
}

export function getPortInfo(slug) {
  const p = port(slug);
  if (!p) return null;
  const ref = p.generatedAt || generatedAt;
  return { name: p.name, rail: p.rail || '', runDate: formatDate(p.runDate || '', ref), generatedAt: ref, notes: p.notes || [], parseError: p.parseError || '' };
}

// True when leadership should try "Update Ramp Dates": a port failed its last
// refresh (parseError), or the whole snapshot has gone stale (bot hasn't run in
// over a week). Drives the subtle pulsing status light.
const STALE_MS = 8 * 24 * 60 * 60 * 1000;
export function refreshNeeded() {
  const ports = schedules.ports || {};
  if (Object.values(ports).some(p => p.parseError)) return true;
  if (pulledAt) {
    const age = Date.now() - new Date(pulledAt).getTime();
    if (isFinite(age) && age > STALE_MS) return true;
  }
  return false;
}

// Published per-destination cut-off time (CN schedules), e.g. "2300 hrs". Empty if none.
export function getCutTime(slug, city) {
  const p = port(slug);
  return (p && p.cutTimes && p.cutTimes[city]) || '';
}

// Vessel names in published order (services stay grouped as on the sheet).
export function getVessels(slug) {
  const p = port(slug);
  return p ? p.vessels.map(v => v.vessel) : [];
}

// US inland ramps that appear in the CPKC/CN schedules. Used only to sort US
// destinations to the top of the city picker. Add new US ramps here if a schedule
// introduces one (everything not listed is treated as Canadian).
const US_CITIES = new Set([
  'MINNEAPOLIS', 'BENSENVILLE', 'DETROIT', 'JEFFERSONVILLE', 'CHIPPEWA FALLS',
  'JOLIET', 'INDIANAPOLIS', 'CHICAGO', 'MEMPHIS', 'NEW ORLEANS', 'ARCADIA',
]);
function isUSCity(city) {
  const key = String(city).toUpperCase().replace(/\(.*?\)/g, '').replace(/[^A-Z ]/g, '').trim();
  return US_CITIES.has(key);
}

export function getCities(slug) {
  const p = port(slug);
  if (!p) return [];
  // US ramps (Detroit, Chicago, …) first; each group keeps its published order.
  return [...p.cities].sort((a, b) => (isUSCity(b) ? 1 : 0) - (isUSCity(a) ? 1 : 0));
}

export function getVesselMeta(slug, vessel) {
  const p = port(slug);
  return p ? p.vessels.find(v => v.vessel === vessel) || null : null;
}

// The published inland cutoff string, e.g. "Mon 29-Jun 18:30".
export function getCutoff(slug, vessel, city) {
  const v = getVesselMeta(slug, vessel);
  return v ? (v.cutoffs[city] || '') : '';
}

// Parse a "Mon 29-Jun 18:30" (or "Mon 29-Jun") cell into a local Date. The PDF
// omits the year, so pick the year (ref-1 / ref / ref+1) whose date lands closest
// to the schedule's own generation date — this survives Dec/Jan wrap-around.
export function parseCutoff(cutoffStr, refISO = generatedAt) {
  const m = String(cutoffStr).match(/(\d{1,2})-([A-Z][a-z]{2})(?:\s+(\d{1,2}):(\d{2}))?/);
  if (!m) return null;
  const day = Number(m[1]);
  const month = MONTHS[m[2]];
  if (month === undefined) return null;
  const hh = m[3] ? Number(m[3]) : 0;
  const mm = m[4] ? Number(m[4]) : 0;

  const [ry, rmo, rd] = String(refISO || '').split('-').map(Number);
  const ref = ry ? new Date(ry, (rmo || 1) - 1, rd || 1) : new Date(2000 + month, month, day);
  const refYear = ref.getFullYear();

  let best = null, bestDiff = Infinity;
  for (const y of [refYear - 1, refYear, refYear + 1]) {
    const d = new Date(y, month, day, hh, mm);
    const diff = Math.abs(d - ref);
    if (diff < bestDiff) { bestDiff = diff; best = d; }
  }
  return best;
}

// House date format: "Fri, 7/24" (weekday, M/D — no leading zeros).
function fmtDate(d) {
  return `${WEEKDAYS[d.getDay()]}, ${d.getMonth() + 1}/${d.getDate()}`;
}

// Weekday for a month(0-indexed)/day, inferring the year from the schedule date.
function weekdayFor(month0, day, refISO) {
  const [ry, rmo, rd] = String(refISO || '').split('-').map(Number);
  const ref = ry ? new Date(ry, (rmo || 1) - 1, rd || 1) : new Date(2000, month0, day);
  const refYear = ref.getFullYear();
  let best = null, bd = Infinity;
  for (const y of [refYear - 1, refYear, refYear + 1]) {
    const d = new Date(y, month0, day);
    const diff = Math.abs(d - ref);
    if (diff < bd) { bd = diff; best = d; }
  }
  return WEEKDAYS[best.getDay()];
}

// Normalize any published date string — "Fri 24-Jul 15:00", "Fri, Jul-03",
// "Tue 7-Jul", "28-Jun", "11-Jul" — to the house format "Fri, 7/24 15:00".
// Keeps the time (24h) when present; computes the weekday when the string omits it.
export function formatDate(str, refISO = generatedAt) {
  if (!str) return str || '';
  const s = String(str).trim();
  const tm = s.match(/(\d{1,2}):(\d{2})/);
  const time = tm ? `${tm[1]}:${tm[2]}` : '';
  let day, month0;
  let m = s.match(/(\d{1,2})-([A-Z][a-z]{2})/);        // D-Mon
  if (m && MONTHS[m[2]] !== undefined) { day = Number(m[1]); month0 = MONTHS[m[2]]; }
  else {
    m = s.match(/([A-Z][a-z]{2})-(\d{1,2})/);          // Mon-DD
    if (m && MONTHS[m[1]] !== undefined) { month0 = MONTHS[m[1]]; day = Number(m[2]); }
  }
  if (day === undefined || month0 === undefined) return str; // unknown shape — leave as-is
  let wd = (s.match(/^([A-Za-z]{3})/) || [])[1];
  if (!wd || !WEEKDAYS.includes(wd)) wd = weekdayFor(month0, day, refISO);
  return `${wd}, ${month0 + 1}/${day}${time ? ' ' + time : ''}`;
}

// ERD (receiving opens). CN publishes it explicitly per destination; CPKC does
// not, so we derive it as the inland cutoff minus 5 days per the PDF note.
// Returned in the "Www D-Mon" style for consistency. Empty if unavailable.
export function getERD(slug, vessel, city) {
  const info = getPortInfo(slug);
  const meta = getVesselMeta(slug, vessel);
  // Published ERD (e.g. CN "28-Jun") takes precedence over the derived rule.
  if (meta && meta.erds && meta.erds[city]) {
    const pub = parseCutoff(meta.erds[city], info && info.generatedAt);
    return pub ? fmtDate(pub) : meta.erds[city];
  }
  const d = parseCutoff(getCutoff(slug, vessel, city), info && info.generatedAt);
  if (!d) return '';
  d.setDate(d.getDate() - ERD_DAYS_BEFORE);
  return fmtDate(d);
}
